### ISSUE TITLE
Clear Collection issue

### ISSUE THREAD

**Issue by EstebanDev0411** [tomio111/builder-server-master#1]
I am using mongodb 4.7.0 in my package.json
"mongodb": "^4.7.0",

but when I try to clear collection, by using remove, it doesn't work.
what's wrong? This is my code.

      const dbConnect = dbo.getDb()
      dbConnect
        .collection(req.query.collection_name)
        .remove()
        .then((data) => {
          res.status(200).send(data)
        })
        .catch((error) => {
          res.status(400).send(error)
        })

**Comment by FancyGeekGuru** [comment]
instead of using remove, you can use deleteOne or deleteMany.
To clear all documents in collection, you can use like this.
  const dbConnect = dbo.getDb()
  dbConnect
    .collection(req.query.collection_name)
    .deleteMan({})
    .then((data) => {
      res.status(200).send(data)
    })
    .catch((error) => {
      res.status(400).send(error)
    })

please check if it works. it is working on my side.

**Comment by EstebanDev0411** [comment]
> instead of using remove, you can use deleteOne or deleteMany. To clear all documents in collection, you can use like this. const dbConnect = dbo.getDb() dbConnect .collection(req.query.collection_name) .deleteMan({}) .then((data) => { res.status(200).send(data) }) .catch((error) => { res.status(400).send(error) })
> 
> please check if it works. it is working on my side.

Thank you. it works. but not deleteMan. maybe deleteMany... anyhow thank you for your help.

**Comment by FancyGeekGuru** [comment]
oh sorry. typo.. you are welcome

> > instead of using remove, you can use deleteOne or deleteMany. To clear all documents in collection, you can use like this. const dbConnect = dbo.getDb() dbConnect .collection(req.query.collection_name) .deleteMan({}) .then((data) => { res.status(200).send(data) }) .catch((error) => { res.status(400).send(error) })
> > please check if it works. it is working on my side.
> 
> Thank you. it works. but not deleteMan. maybe deleteMany... anyhow thank you for your help.
